name: Build image and push to Container Registry

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout repo ke dalam proses workflow
      - name: Checkout
        uses: actions/checkout@v2

      # Setup QEMU & Buildx (diperlukan untuk build image multi arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      # Login, build, dan push image ke Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Buildx (push)
        run: |
          docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          --file ./Dockerfile ./
